name: deploy dev
on:
  push:
    branches: [dev]

jobs:

  deploy_to_dev:
    name: Deploy to development env
    runs-on: ubuntu-latest
    env:
      TELEGRAM_TO: ${{secrets.TELEGRAM_TO}}
      TELEGRAM_TOKEN: ${{secrets.TELEGRAM_TOKEN}}
    steps:
      - name: executing remote ssh commands using password
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          script: |
            cd ~/work/overmint/overmint/frontend-next
            git pull origin dev
            cd ~/work/overmint/overmint/
            docker-compose up --build frontend -d
      - name: send telegram message on deploy to develop environment
        uses: appleboy/telegram-action@master
        with:
          to: ${{ env.TELEGRAM_TO }}
          token: ${{ env.TELEGRAM_TOKEN }}
          message: |
            [DEV]
            ${{ github.actor }} push on ${{github.ref_name}} - deploy successfully
            Repository: ${{ github.repository }}
            See changes: https://github.com/${{ github.repository }}/commit/${{github.sha}}
